"""Add cookie_topping

Revision ID: d6c4430a0051
Revises: 8d45819be783
Create Date: 2022-05-08 04:39:33.569269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c4430a0051'
down_revision = '8d45819be783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookie_toppings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cookie_id', sa.Integer(), nullable=False),
    sa.Column('part_num', sa.Integer(), nullable=False),
    sa.Column('part_pos', sa.Integer(), nullable=False),
    sa.Column('is_lock', sa.BOOLEAN(), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=64), nullable=True),
    sa.Column('top_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cookies', sa.Column('cool_time', sa.Integer(), nullable=False))
    op.drop_column('cookies', 'top_id')
    op.drop_column('cookies', 'part_num')
    op.drop_column('cookies', 'part_pos')
    op.drop_column('cookies', 'is_lock')
    op.drop_column('cookies', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('desc', sa.VARCHAR(length=64), nullable=True))
    op.add_column('cookies', sa.Column('is_lock', sa.BOOLEAN(), nullable=False))
    op.add_column('cookies', sa.Column('part_pos', sa.INTEGER(), nullable=False))
    op.add_column('cookies', sa.Column('part_num', sa.INTEGER(), nullable=False))
    op.add_column('cookies', sa.Column('top_id', sa.INTEGER(), nullable=True))
    op.drop_column('cookies', 'cool_time')
    op.drop_table('cookie_toppings')
    # ### end Alembic commands ###
